### ISSUE TITLE
Research: Choose possible fonts

### ISSUE THREAD

**Issue by jjcourtney** [jjcourtney/PDJ#17]
Look at fonts that are available narrow down to 4 options for "InfoCraft"

**Comment by jjcourtney** [comment]
![fonts](https://user-images.githubusercontent.com/63928634/125933485-ac0e2570-cb50-456c-8977-4746a34f4da7.png)

**Comment by odders17** [comment]
Look great Jon permanent marker and orbitron are particularly good

**Comment by jjcourtney** [comment]
https://fonts.google.com/specimen/Press+Start+2P

found this one too!
