### ISSUE TITLE
Check feasibility of APIs

### ISSUE THREAD

**Issue by jjcourtney** [jjcourtney/PDJ#3]
GIVEN an API
WHEN I use a fetch request
THEN I get a JSON as a response
WHEN I  get a JSON as a response
THEN I have the correct information back

**Comment by odders17** [comment]
Checked google translate API matches criteria 
limited to 500 calls per month

**Comment by jjcourtney** [comment]
Checked D7 SMS - Does not meet requirements
Further checks into other APIs - Node.js implementations seem to be the most plausible
