### ISSUE TITLE
Feasibility for https://api.hypixel.net/

### ISSUE THREAD

**Issue by jjcourtney** [jjcourtney/PDJ#4]
Acceptance Criteria

GIVEN the api - https://api.hypixel.net/
WHEN I query a players name
THEN I get back their stats on Hypixel

**Comment by Dylson14** [comment]
LGTM

**Comment by Dylson14** [comment]
It requires another API to work. Have a look at this link here([https://api.mojang.com/users/profiles/minecraft/<username>])

**Comment by odders17** [comment]
This link work, great stuff
