### ISSUE TITLE
Check for a way to view minecraft skins 

### ISSUE THREAD

**Issue by jjcourtney** [jjcourtney/PDJ#5]
Check for APIs and resources for viewing  Minecraft skins

AS a user
WHEN I load the page
I CAN view a given Minecraft skin for a give UUID

**Comment by jjcourtney** [comment]
https://api.mojang.com/users/profiles/minecraft/<username>
this seems like the best one - returns a png - so could use as the src in an img tag.

**Comment by odders17** [comment]
Yes this looks fine. Go for it
