### ISSUE TITLE
Framework: Tailwind

### ISSUE THREAD

**Issue by jjcourtney** [jjcourtney/PDJ#8]
Check viability of using tailwind for CSS framework

**Comment by odders17** [comment]
Tailwind looks good, I think we need to use a CDN for it. Found This Link https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.2/tailwind.min.css

**Comment by jjcourtney** [comment]
That looks great!

**Comment by Dylson14** [comment]
I agree with Jon, good stuff Paul!
